from connessione import connessione_al_db
from tqdm import tqdm

def crea_db():
    conn = connessione_al_db()
    if conn is None:
        print("Connessione al database fallita.")
        return
    
    cursor = conn.cursor()

    
    # ORACLE utilizza il linguaggio PL/SQL (Procedural Language/SQL) #
    # Possiamo vederlo come una estensione del MySQL.
    # Mentre Oracle e progettato per sicurezza e rigidita militare
    # Mysql e progettato per veloce, leggero e flessibile
    # VARCHAR = VARCHAR2
    # AUTO_INCREMENT = GENERATED BY DEFAULT AS IDENTIFY
    
    try:
        # cursor.execute("USE STRADA")
        # In Oracle non esiste "USE STRADA", i dati vanno nello schema dell'utente con cui ti connetti
        
        # drop_queries = [
        # "DROP TABLE IF EXISTS incidenti_fattori;",
        # "DROP TABLE IF EXISTS incidenti_veicoli;",
        # "DROP TABLE IF EXISTS incidenti;",
        # "DROP TABLE IF EXISTS volume_traffico;",
        # "DROP TABLE IF EXISTS taxi;",
        # "DROP TABLE IF EXISTS meteo;"
        # ]
        drop_queries = [
            "DROP TABLE incidenti_fattori CASCADE CONSTRAINTS",
            "DROP TABLE incidenti_veicoli CASCADE CONSTRAINTS",
            "DROP TABLE incidenti CASCADE CONSTRAINTS",
            "DROP TABLE volume_traffico CASCADE CONSTRAINTS",
            "DROP TABLE taxi CASCADE CONSTRAINTS",
            "DROP TABLE meteo CASCADE CONSTRAINTS"
        ]
        # queries = [
        # """
        # CREATE TABLE IF NOT EXISTS incidenti (
        #     id_incidente INT PRIMARY KEY,
        #     accident_date DATE,
        #     accident_time TIME,
        #     borough VARCHAR(50),
        #     zip_code VARCHAR(10),
        #     latitude DECIMAL(10,7),
        #     longitude DECIMAL(10,7),
        #     on_street_name VARCHAR(100),
        #     cross_street_name VARCHAR(100),
        #     off_street_name VARCHAR(100),
        #     persons_injured INT,
        #     persons_killed INT,
        #     pedestrians_injured INT,
        #     pedestrians_killed INT,
        #     cyclist_injured INT,
        #     cyclist_killed INT,
        #     motorist_injured INT,
        #     motorist_killed INT
        # );
        # """,
        # """
        # CREATE TABLE IF NOT EXISTS incidenti_fattori (
        #     id INT AUTO_INCREMENT PRIMARY KEY,
        #     id_incidente INT,
        #     contributing_factor VARCHAR(250),
        #     FOREIGN KEY (id_incidente) REFERENCES incidenti(id_incidente) ON DELETE CASCADE
        # );
        # """,
        # """
        # CREATE TABLE IF NOT EXISTS incidenti_veicoli (
        #     id INT AUTO_INCREMENT PRIMARY KEY,
        #     id_incidente INT,
        #     vehicle_type VARCHAR(250),
        #     FOREIGN KEY (id_incidente) REFERENCES incidenti(id_incidente) ON DELETE CASCADE
        # );
        # """,
        # """
        # CREATE TABLE IF NOT EXISTS volume_traffico (
        #     id INT AUTO_INCREMENT PRIMARY KEY,
        #     request_id INT,
        #     boro VARCHAR(50),
        #     anno YEAR,
        #     mese TINYINT,
        #     giorno TINYINT,
        #     ora TINYINT,
        #     minuto TINYINT,
        #     volume INT,
        #     segment_id INT,
        #     street VARCHAR(100),
        #     from_st VARCHAR(100),
        #     to_st VARCHAR(100),
        #     direction VARCHAR(10)
        # );
        # """,
        # """
        # CREATE TABLE IF NOT EXISTS taxi (
        #     id_corsa BIGINT AUTO_INCREMENT PRIMARY KEY,
        #     vendor_id INT,
        #     pickup_datetime DATETIME,
        #     dropoff_datetime DATETIME,
        #     passenger_count INT,
        #     trip_distance DECIMAL(8,2),
        #     pickup_longitude DECIMAL(10,7),
        #     pickup_latitude DECIMAL(10,7),
        #     dropoff_longitude DECIMAL(10,7),
        #     dropoff_latitude DECIMAL(10,7),
        #     ratecode_id INT,
        #     payment_type INT,
        #     fare_amount DECIMAL(8,2),
        #     tip_amount DECIMAL(8,2),
        #     tolls_amount DECIMAL(8,2),
        #     total_amount DECIMAL(8,2)
        # );
        # """,
        # """
        # CREATE TABLE IF NOT EXISTS meteo (
        #     id_meteo INT AUTO_INCREMENT PRIMARY KEY,
        #     precipitazioni DECIMAL(6,2),
        #     data DATE,
        #     neve DECIMAL(6,2),
        #     neve_suolo DECIMAL(6,2),
        #     temperatura_min DECIMAL(5,2),
        #     temperatura_max DECIMAL(5,2)
        # );
        # """]
        queries = [
        """
        CREATE TABLE incidenti (
            id_incidente INT PRIMARY KEY,
            accident_date DATE,
            accident_time VARCHAR2(10),
            borough VARCHAR2(50),
            zip_code VARCHAR2(50),
            latitude DECIMAL(10,7),
            longitude DECIMAL(10,7),
            on_street_name VARCHAR2(100),
            cross_street_name VARCHAR2(100),
            off_street_name VARCHAR2(100),
            persons_injured INT,
            persons_killed INT,
            pedestrians_injured INT,
            pedestrians_killed INT,
            cyclist_injured INT,
            cyclist_killed INT,
            motorist_injured INT,
            motorist_killed INT
        )
        """,
        """
        CREATE TABLE incidenti_fattori (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_incidente INT,
            contributing_factor VARCHAR2(250),
            FOREIGN KEY (id_incidente) REFERENCES incidenti(id_incidente) ON DELETE CASCADE
        )
        """,
        """
        CREATE TABLE incidenti_veicoli (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_incidente INT,
            vehicle_type VARCHAR2(250),
            FOREIGN KEY (id_incidente) REFERENCES incidenti(id_incidente) ON DELETE CASCADE
        )
        """,
        """
        CREATE TABLE volume_traffico (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_incidente INT, -- <--- AGGIUNTA: Collega il traffico all'incidente avvenuto in quella zona/ora
            request_id INT,
            boro VARCHAR2(50),
            anno NUMBER(4),
            mese NUMBER(2),
            giorno NUMBER(2),
            ora NUMBER(2),
            minuto NUMBER(2),
            volume INT,
            segment_id INT,
            street VARCHAR2(100),
            from_st VARCHAR2(100),
            to_st VARCHAR2(150),
            direction VARCHAR2(10),
            FOREIGN KEY (id_incidente) REFERENCES incidenti(id_incidente) ON DELETE SET NULL
        )
        """,
        """
        CREATE TABLE taxi (
            id_corsa NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_incidente INT, -- <--- AGGIUNTA: Collega una corsa di taxi che si trovava nelle vicinanze di un incidente
            vendor_id INT,
            pickup_datetime TIMESTAMP,
            dropoff_datetime TIMESTAMP,
            passenger_count INT,
            trip_distance DECIMAL(12,2),
            pickup_longitude DECIMAL(10,7),
            pickup_latitude DECIMAL(10,7),
            dropoff_longitude DECIMAL(10,7),
            dropoff_latitude DECIMAL(10,7),
            ratecode_id INT,
            payment_type INT,
            fare_amount DECIMAL(12,2),
            tip_amount DECIMAL(12,2),
            tolls_amount DECIMAL(12,2),
            total_amount DECIMAL(12,2),
            FOREIGN KEY (id_incidente) REFERENCES incidenti(id_incidente) ON DELETE SET NULL
        )
        """,
        """
        CREATE TABLE meteo (
            id_meteo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            data_meteo DATE UNIQUE, -- <--- AGGIUNTA: UNIQUE permette di usarla come chiave esterna logica per la data
            precipitazioni DECIMAL(6,2),
            neve DECIMAL(6,2),
            neve_suolo DECIMAL(6,2),
            temperatura_min DECIMAL(5,2),
            temperatura_max DECIMAL(5,2)
        )
        """,
        # """
        # CREATE TABLE admins(
        #     id_admin NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        #     username VARCHAR2(25),
        #     passwd VARCHAR2(255),
        #     tutti_permessi NUMBER(1) DEFAULT 0, 
        #     CONSTRAINT chk_tutti_permessi CHECK (tutti_permessi IN (0, 1)) 
        # )
        # """
        ]


        for query in tqdm(drop_queries):
            try:
                cursor.execute(query)
                nome_tabella = query.split()
                nome_tabella = nome_tabella[2].replace(';', '').title()
                print(f"Tabella eliminata con successo: {nome_tabella} ")
                
                conn.commit()
            
            except Exception as e:
                print(f"Errore durante l'eliminazione della tabella: {e}")
            
        for query in tqdm(queries):
            try:
                cursor.execute(query)
                nome_tabella = query.split()
                nome_tabella = nome_tabella[2].title()
                print(f"Tabella creata con successo: {nome_tabella} ")
                
                conn.commit()
            
            except Exception as e:
                print(f"Errore durante la creazione della tabella: {e}")
                
    except Exception as e:
        print(f"Ce stato un errore: {e}")   
    
    finally:         
        cursor.close()           
        conn.close()

if __name__ == '__main__':
    crea_db()